### ISSUE TITLE
Issue with code running indefinitely when the data is more.

### ISSUE THREAD

**Issue by vinayakbhatt92** [konosp/adobe-analytics-reports-api-v2.0#11]
Hi Mayhem,

Thanks alot for the python Package analytics mayhem this has been a game changer for me. I am using it to extract out data from adobe analytics.
The only problem I am facing is that it is taking alot of time in running the code as its  just running indefinitely and I had to close the command. I am really sorry I am writing this question but I dont know how to connect with you via any other method.
It would be great if you could help me on this as there is nothing like this package on the net.

Regards,
Vinayak

**Comment by konosp** [comment]
Hi @vinayakbhatt92 ,

Thanks for your feedback. 

- Can you please clarify if the code eventually completes successfully or just dies? 
- How many dimensions do you add to the report? If you try less dimensions, is the execution completing successfully?

I am wondering if this is because it's just way too much data and takes a lot of time.

I might have to add some logging in the console to make monitoring of the execution easier.

Cheers, Konstantinos

**Comment by vinayakbhatt92** [comment]
HI  Konstantinos,

Thanks alot for this,
1.Can you please clarify if the code eventually completes successfully or
just dies?
The is just runs for 20-30 mins before I terminate it.The date range I used
was for two days.

2.How many dimensions do you add to the report? If you try less dimensions,
is the execution completing successfully?
The maximun dimension I tried were 3 and the minimum was 1.

The data is not much as per my understanding but if this is the case is
there any way to optimize it so that we can run it daily.
And thanks again for replying to my mail.
Regards,
Vinayak

**Comment by konosp** [comment]
Thanks @vinayakbhatt92 , will try to add some logging in the console to see what the behavior is like. 

Some additional questions, have you seen the issue occurring for small amounts of data as well? 

Do you run multiple processes with the same service account? Adobe has a max limit of requests per minute on account basis. So if you have multiple processes using the same account, maybe this is causing the issue.

Let me know what you think.

**Comment by vinayakbhatt92** [comment]
Hi Konstantinos,

have you seen the issue occurring for small amounts of data as well? - yes
when the number of dimensions is more than one.
Do you run multiple processes with the same service account? - We are the
only one using that personal account using APIs.

Regards,
Vinayak

**Comment by konosp** [comment]
Hi @vinayakbhatt92,

I have added extended logging in the staging branch of the package. Can you please perform the following and let me know what results you observe in the terminal when you execute it?

1. Uninstall the local package by running `pip uninstall analytics-mayhem-adobe`
2. Install the staging branch by running `pip install git+https://github.com/konosp/adobe-analytics-reports-api-v2.0.git@stage`
3. When you initiate the client, add the additional flag `aa = analytics_client(<arguments>, debugging=True)`

The above will activate logging, show you the kind of operations that take place along with the results that the API requests return back to your client. I will need to see those logs and have a better idea of the issue. In case there is information that you would not like to share, please modify the numbers/values but please do not alter the structure of the logs.

Cheers,
Konstantinos

**Comment by konosp** [comment]
Hi @vinayakbhatt92 ,

Please let me know if the above helped.

Cheers, Konstantinos

**Comment by vinayakbhatt92** [comment]
HI Konstantinos,

I am extremely sorry for replying so late..
I was caught up dowsing other fires(even relatively smaller things take
alot of time for new people like me)  and could not give time towards this
as API.
Terribly sorry for this.
I received an error for the same which is :
ERROR: Error [WinError 2] The system cannot find the file specified while
executing command git clone -q
https://github.com/konosp/adobe-analytics-reports-api-v2.0.git
'C:\Users\773363\AppData\Local\Temp\pip-req-build-ysglu8fb'
ERROR: Cannot find command 'git' - do you have 'git' installed and in your
PATH?

I work from a computer where I dont have much permissions if that the
reason I am not able to install from git+http

Regards,
Vinayak

**Comment by konosp** [comment]
This issue might relate when executing code with a single dimension but calling aa.get_report_multiple_breakdowns().

**Comment by vinayakbhatt92** [comment]
Hi Konstantine

Thanks for the Email not sure on that as dimensions are more than that

Regards
Vinayak

**Comment by konosp** [comment]
Thanks @vinayakbhatt92. Thought to double check as this scenario causes the code to hang. I need to fix it. Not sure at the moment what else might be causing this.

**Comment by vinayakbhatt92** [comment]
Hi Konstantinos
The code just runs on an infinite loop

Regards
Vinayak

**Comment by joaoferrao** [comment]
hi @konosp I seem to have run into the same issue. By "running indefinitely", I mean that it keeps iterating through what appears is the same page.

e.g. taken from the debugging logs:

```json
Parsing page 10:
{"totalPages":2,"firstPage":true,"lastPage":false,"numberOfElements":50,...
```

...
...
...

A few rows down it's on page 502, with 100% same contents:

```json
Parsing page 502
{"totalPages":2,"firstPage":true,"lastPage":false,"numberOfElements":50,...
```

I have verified, and throughout all iterations, the contents of the responses is 100% the same at this point and it goes on to 1000+ pages before I quite and decide to exit the process.

**Comment by joferrao** [comment]
I think I may have found the reason for this. When the result has more than one page on a custom report, the `get_report()` method does not update the `custom_report_object["settings"]["page"]` and gets stuck in a loop

This happens when `custom_report_object` is not None and there is than 1x page in the results.

```
    def get_report(self, custom_report_object = None):
        self._set_page_number(0)
        # Get initial page
        data = self._get_page(custom_report_object)
        self.logger(data.text)
        json_obj = json.loads(data.text)
        total_pages = json_obj['totalPages']
        current_page = 1
        is_last_page = False
        df_data = self.format_output(data)
        # Download additional data if more than 1 pages are available
        while (total_pages > 1 and not is_last_page):
            self.logger('Parsing page {}'.format(current_page))
            self._set_page_number(current_page)
            data = self._get_page(custom_report_object)
            self.logger(data.text)
            json_obj = json.loads(data.text)
            is_last_page = json_obj['lastPage']
            current_page = current_page + 1
            df_current_page = self.format_output(data)

            df_data = df_data.append(df_current_page, ignore_index=True)

        return df_data
```

**Comment by konosp** [comment]
Hi @joaoferrao thanks for flagging this.

I will try to have a look over the weekend. However if you have the time, feel free to create a pull request with the fix. That would be extremely helpful. Otherwise I will try to have a look as soon as I get some time.

Thank you!

**Comment by joaoferrao** [comment]
@konosp it seems I am not allowed to push branches:
```shell
 $  git push origin feature_multiple-page-resp
ERROR: Permission to konosp/adobe-analytics-reports-api-v2.0.git denied to joaoferrao.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by konosp** [comment]
@joaoferrao   You will need to fork the project, make the changes and the perform a pull request.
I think the instructions here would help. 

https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by konosp** [comment]
@joaoferrao I have managed to reproduce the bug finally. Thanks for your comments.
Will try to resolve it.

**Comment by konosp** [comment]
Hi @joaoferrao 

I have added somewhat of a fix. It's now on the staging branch. 

Do you mind giving it a go and let me know how it works for you?

1. Uninstall the local package by running pip uninstall analytics-mayhem-adobe
2. Install the staging branch by running pip install git+https://github.com/konosp/adobe-analytics-reports-api-v2.0.git@stage

Let me know for your feedback.

Thanks!

**Comment by joaoferrao** [comment]
@konosp incredible thanks for the quick reaction. We are trying to test your new changes and will let you know. We really appreciate the work you have done with this client.
