### ISSUE TITLE
Private key de-serialization issue

### ISSUE THREAD

**Issue by lauraperge** [konosp/adobe-analytics-reports-api-v2.0#24]
I have worked with your package for more than half a year now, and ran the same code over and over again without any issues. Suddenly, I cannot run it now, as it fails with the below error. My pem file is the same as ever, and the key is not expired. I tried updating the cryptography package but it solves nothing. I tried downgrading the cryptography package, same issue. I'm using version 0.0.8 on Windows, Python 3.7.
Would highly appreciate your help.

> TypeError                                 Traceback (most recent call last)
> <command-534597992702760> in <module>
>      19 aa.add_dimension(dimension_name = 'variables/daterangeday')
>      20 
> ---> 21 df0 = aa.get_report()
> 
> /local_disk0/pythonVirtualEnvDirs/virtualEnv-c9976e96-acb1-4a62-9656-e4d1a21b6ef1/lib/python3.7/site-packages/analytics/mayhem/adobe.py in get_report(self, custom_report_object)
>     289         self._set_page_number(0)
>     290         # Get initial page
> --> 291         data = self._get_page(custom_report_object)
>     292         self.logger(data.text)
>     293         json_obj = json.loads(data.text)
> 
> /local_disk0/pythonVirtualEnvDirs/virtualEnv-c9976e96-acb1-4a62-9656-e4d1a21b6ef1/lib/python3.7/site-packages/analytics/mayhem/adobe.py in _get_page(self, report_object)
>     255             report_object = self.report_object
>     256 
> --> 257         analytics_header = self._get_request_headers()
>     258 
>     259         status_code = None
> 
> /local_disk0/pythonVirtualEnvDirs/virtualEnv-c9976e96-acb1-4a62-9656-e4d1a21b6ef1/lib/python3.7/site-packages/analytics/mayhem/adobe.py in _get_request_headers(self)
>     150             self.access_token = self._obtain_oauth_access_token()
>     151         elif self.client_id:
> --> 152             self.access_token = self._renew_access_token()
>     153 
>     154         analytics_header = {
> 
> /local_disk0/pythonVirtualEnvDirs/virtualEnv-c9976e96-acb1-4a62-9656-e4d1a21b6ef1/lib/python3.7/site-packages/analytics/mayhem/adobe.py in _renew_access_token(self)
>     101         jwtPayloadJson = self._get_jwtPayload()
>     102         # Encode the jwt Token
> --> 103         jwttoken = jwt.encode(jwtPayloadJson, private_key, algorithm='RS256')
>     104 
>     105         accessTokenRequestPayload = {
> 
> /local_disk0/pythonVirtualEnvDirs/virtualEnv-c9976e96-acb1-4a62-9656-e4d1a21b6ef1/lib/python3.7/site-packages/jwt/api_jwt.py in encode(self, payload, key, algorithm, headers, json_encoder)
>      61         ).encode("utf-8")
>      62 
> ---> 63         return api_jws.encode(json_payload, key, algorithm, headers, json_encoder)
>      64 
>      65     def decode_complete(
> 
> /local_disk0/pythonVirtualEnvDirs/virtualEnv-c9976e96-acb1-4a62-9656-e4d1a21b6ef1/lib/python3.7/site-packages/jwt/api_jws.py in encode(self, payload, key, algorithm, headers, json_encoder)
>     108         try:
>     109             alg_obj = self._algorithms[algorithm]
> --> 110             key = alg_obj.prepare_key(key)
>     111             signature = alg_obj.sign(signing_input, key)
>     112 
> 
> /local_disk0/pythonVirtualEnvDirs/virtualEnv-c9976e96-acb1-4a62-9656-e4d1a21b6ef1/lib/python3.7/site-packages/jwt/algorithms.py in prepare_key(self, key)
>     240                         key = load_ssh_public_key(key)
>     241                     else:
> --> 242                         key = load_pem_private_key(key, password=None)
>     243                 except ValueError:
>     244                     key = load_pem_public_key(key)
> 
> TypeError: load_pem_private_key() missing 1 required positional argument: 'backend'

**Comment by konosp** [comment]
Hi @lauraperge,

I found online a similar issue mentioning that this might be related to a package conflict.
https://stackoverflow.com/questions/63738152/deserializing-public-key-with-pythons-cryptography-module/63738463#63738463

Do you think you have other packages that might create this issue?
It is worth re-installing the package in a clean virtual environment and try again?

Let me know if this works for you.

Cheers

**Comment by lauraperge** [comment]
@konosp we moved to a different solution, so I cannot confirm if that solves the issue but I am fairly sure it is a package conflict as well. Thank you for the answer!
