### ISSUE TITLE
Support OAuth2 Authentication

### ISSUE THREAD

**Issue by konosp** [konosp/adobe-analytics-reports-api-v2.0#5]
Documentation: https://github.com/AdobeDocs/analytics-2.0-apis/blob/master/oauth-curl.md

**Comment by melanoma** [comment]
Came here to request this. My org unfortunately does not provide me access for JWT. Your project looks great and I would really like to try it. Thanks!

**Comment by konosp** [comment]
Hi @melanoma, had in mind for a long time to do this. Just never had the chance. will try to pick this up again! will keep you posted!

**Comment by konosp** [comment]
Hi @melanoma Have updated the appropriate branch to support OAuth authentication (https://github.com/konosp/adobe-analytics-reports-api-v2.0/tree/feature-oauth-authentication). Would you mind giving it a try?
To so you will need:

1. Install the appropriate branch from git by running `pip install git+https://github.com/konosp/adobe-analytics-reports-api-v2.0.git@feature-oauth-authentication`. This would install locally this particular branch. In case you have previously installed the version from PyPI you will need to uninstall it by `pip uninstall analytics-mayhem-adobe`
2. Create an OAuth integration in the adobe console. Follow the instructions at  https://github.com/AdobeDocs/analytics-2.0-apis/blob/master/create-oauth-client.md
3. Try the notebook created at https://github.com/konosp/adobe-analytics-reports-api-v2.0/blob/feature-oauth-authentication/OAuth%20Demo.ipynb

Let me know how it goes so I can push it into the live version!
Cheers

**Comment by konosp** [comment]
Hi @melanoma , any chance you looked into this? Eager to know if it works for you without issues. Cheers
